---
- include_tasks: prep_linux.yaml
  when: |
    ansible_facts['os_family'] == 'Debian' or
    ansible_facts['os_family'] == 'Redhat'

- include_tasks: prep_macos.yaml
  when: ansible_facts['os_family'] == 'Darwin'

- name: Install borgmatic
  community.general.pipx:
    name: borgmatic
    state: present

- name: Make sure the borgmatic configs directory structure is set up
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "/etc/borgmatic/"
    - "/etc/borgmatic.d/"

- name: Template all YAML configuration files from files/borgmatic
  template:
    src: "{{ item }}"
    dest: "/etc/borgmatic.d/{{ item | basename }}"
  with_fileglob: "{{ playbook_dir }}/files/borgmatic/*.yaml"

- name: Initialize borgmatic
  command:
    cmd: "borgmatic init --encryption {{ borgmatic_encryption_mode }}"
  register: init
  changed_when: false
  failed_when:
    - "'Failed to create/acquire the lock' not in init.stderr"
    - - init.rc != 0
